### PR TITLE
speedup travis-ci builds by appling 

### PR DESCRIPTION
**Pull request by loechel**
https://community.plone.org/t/clean-ish-way-to-get-travis-to-build-all-plone-versions/2539/14

@jensens could please have a quick look, if that is OK.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by jensens** [comment]
I would use @hvelarde s optimized approach which is meanwhile part of bobtemplates.plone. 
But yours should work as well.

**Comment by loechel** [comment]
@jensens I either don't see @hvelarde optimized approach, or is it: https://github.com/plone/bobtemplates.plone/blob/master/bobtemplates/plone_addon/.travis.yml.bob Lines 3-6 + 13/14

That won't work here, as tox is in use and tox runs the buildout.

**Comment by loechel** [comment]
at least I now see a significant speedup tests on travis are now under 5 Minutes instead of 15-20 Minutes before.

**Comment by hvelarde** [comment]
it isn't my approach, is Travis CI standard approach and, yes, is way simpler and, yes, it will work here because it's on the container level:

https://docs.travis-ci.com/user/caching/

on the other side, please don't add yet another way to run tests; that needs a PLIP as it needs to be discussed, understood and accepted by everyone.

**Comment by loechel** [comment]
@hvelarde well I either don't get it, or we are speaking about different things. The cache settings with directories is Travis standard and the way to go. But I do see a different in the way the buildout is invoked on the mr.bob template and I am doing it here. This invokation of buildout is not possible and useful with tox, the .buildout/default.cfg instead is perfect for local and ci test runner.

Your other side: not another way of running tests is not a way to go. I did thought that the testing team must have already proposed to move to tox, if not that will definetly come.

There is just no other way of doing tests in future as we need to support multiple versions on Python and Plone for some packages / addons.

**Comment by hvelarde** [comment]
I hope everything is clear now we have talked.

**Comment by loechel** [comment]
@hvelarde Yes I do see your points and understand what you have tried. 

But I still did not see how that could be incorporated with the current setup of this package.
As it is no core package and not an official add-on it does not matter if we test potential new best practice approaches here. I would like to stay on tox and travis test with one setup. So one core element of the caching would not work with the current described approache in bobtemplates.plone.

For tox I have created a PLIP: https://github.com/plone/Products.CMFPlone/issues/2072

**Pull request merged**
