### PR TITLE
Schema change

### PR DESCRIPTION
**Pull request by ghost**
Added additional fields to the schema to retrieve useful information from PyPI

addresses #6

### CODE REVIEW

**Comment by ghost** [comment]
Which option would be better for downloads- Sum of download count of all release versions or download count of the latest version?

**Comment by ghost** [comment]
Is it fine to use the upload time of the first version to determine the newest / recently added addons?

**Comment by loechel** [comment]
Hi @pavithirakc,

the download sum I have added was for total, but it would as you might seen on the post from zopyx, to have two fields, download_sum_total and download_sum_latest

As one version could have multiple uploaded Distribution files, and every of those got count separately, that would make sense. 

So it is just a helper field, that store the date that would be shown, as recalculate on every browser view would be expensive.

I am not sure if the list of versions is sorted by adding time or version key. So you might have to look at all versions to look and their upload time to determine the newest.

**Comment by tkimnguyen** [comment]
@loechel do you want to review the PR and/or approve the merging and then do the merging? If you don't have time let me know and I can proceed.

**Comment by loechel** [comment]
@tkimnguyen As long as it is flaged WIP I will not review or merge it.
As soon as @pavithirakc change the state and request for merge I will review and merge.

**Comment by tkimnguyen** [comment]
Ah, ok, I was fooled by this: 
screenshot

**Review by loechel — APPROVED** [review]

**Comment by loechel** [comment]
@pavithirakc Thanks

**Pull request merged**
